apiVersion: v1
kind: Service
metadata:
  name: payments-service-example
  labels:
    app: payments-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: payments-service
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-service-deployment
  labels:
    app: payments-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-service
  template:
    metadata:
      labels:
        app: payments-service
    spec:
      containers:
      - name: payments-service-example-container
        image: 894577096821.dkr.ecr.us-east-1.amazonaws.com/payments-service-example:latest
        ports:
        - containerPort: 80