apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{SERVICE_NAME}}"
  labels:
    app: "{{SERVICE_NAME}}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{SERVICE_NAME}}"
  template:
    metadata:
      labels:
        app: "{{SERVICE_NAME}}"
    spec:
      nodeSelector:
        env: "{{ENVIRONMENT}}"
      containers:
        - name: "{{SERVICE_NAME}}"
          image: "{{REGISTRY}}/{{SERVICE_NAME}}:{{TAG}}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 256Mi
              cpu: "0.5"
            limits:
              memory: 512Mi
              cpu: "1"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: "{{SERVICE_NAME}}-service"
spec:
  selector:
    app: "{{SERVICE_NAME}}"
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080