apiVersion: v1
kind: Service
metadata:
  name: payments-service-example
  labels:
    app: payments-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: payments-service
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-service-deployment
  labels:
    app: payments-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-service
  template:
    metadata:
      labels:
        app: payments-service
    spec:
      containers:
      - name: payments-service-example-container
        # The $REPOSITORY_URI and $IMAGE_TAG placeholders will be replaced by actual values supplied by the build action in your workflow
        image: $REPOSITORY_URI:$IMAGE_TAG
        ports:
        - containerPort: 80