name: Generate Infrastructure

on:
  workflow_dispatch:
env:
  TERRAFORM_WORKING_DIR: terraform
  TF_VAR_environment: ${{ vars.ENVIRONMENT }}
  TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
  TF_VAR_aws_region: ${{ vars.AWS_REGION }}
  TF_VAR_role_arn: ${{ secrets.AWS_ROLE_ARN }}
  TF_VAR_repository: ${{ github.event.repository.name }}

jobs:
  setup_infra:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform_version:
          - 1.9.1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        working-directory: ${{ env.TERRAFORM_WORKING_DIR }}
        continue-on-error: true
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TERRAFORM_WORKING_DIR }}
      - name: Terraform Validate
        run: terraform validate -no-color
        working-directory: ${{ env.TERRAFORM_WORKING_DIR }}
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.TERRAFORM_WORKING_DIR }}
