name: Push image to ECR

on:
  workflow_dispatch:
env:
  TERRAFORM_WORKING_DIR: terraform
  TF_VAR_environment: ${{ vars.ENVIRONMENT }}
  TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
  TF_VAR_aws_region: ${{ vars.AWS_REGION }}
  TF_VAR_role_arn: ${{ secrets.AWS_ROLE_ARN }}
  TF_VAR_repository: ${{ github.event.repository.name }}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version:
          - 8.0.x
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-artifact.jar
          path: target/*.jar
  set_up_ecr:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform_version:
          - 1.9.1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        working-directory: ${{ env.TERRAFORM_WORKING_DIR }}
        continue-on-error: true
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TERRAFORM_WORKING_DIR }}
      - name: Terraform Validate
        run: terraform validate -no-color
        working-directory: ${{ env.TERRAFORM_WORKING_DIR }}
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.TERRAFORM_WORKING_DIR }}
        continue-on-error: true
  generate_image:
    needs:
      - build
      - set_up_ecr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: "true"
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-artifact.jar
          path: ./java-artifact.jar
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.TF_VAR_repository }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:latest .
          docker push $REGISTRY/$REPOSITORY --all-tags
