name: SonarCloud scan

on:
  pull_request: 
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      ecr_repository: ${{ steps.set_repo_name.outputs.ECR_REPOSITORY }}
    strategy:
      matrix:
        java-version:
          - 8.0.x
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Set file name as repository name
        id: set_repo_name
        run: echo "ECR_REPOSITORY=$(mvn help:evaluate -Dexpression=project.name -q -DforceStdout)" >> "$GITHUB_OUTPUT"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-artifact.jar
          path: target/*.jar

  sonarcloud:
    needs:
      - build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2.3.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
          -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
          -Dsonar.java.binaries=**/target/